language: node_js
node_js:
    - "lts/*"
notifications:
    email: false
cache: false
sudo: required
script: skip
jobs:
    include:
        - stage: lint
          script: npm run lint
        - stage: test
          script: npm run test
        - stage: build
          script: npm run build
stages:
    - lint
    - test
    - build
